name: compile_and_test

on:
  push:
    branches: [ devops ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: make
      working-directory: ./akdb/src
      
    - name: run all tests
      run: ./akdb | ./akdb alltest
      working-directory: ./akdb/bin
      
    - name: compile doc 
      run: make doc
      working-directory: ./akdb/doc
