name: compile_and_test

on:
  push:
    branches: [ devops ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: make
      working-directory: ./akdb/src
      
    #- name: run all tests
    #  run: ./akdb | ./akdb alltest
    #  working-directory: ./akdb/bin
      
    - name: compile doc 
      uses: mattnotmitt/doxygen-action@v1
      with:
        working-directory: ./akdb/src
        doxyfile-path: ./akdb/doc
        enable-latex: true
        run: make doc
          
    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        # Make sure you have that / at the end. We use rsync 
        # WIKI_DIR's default is wiki/
        WIKI_DIR: ./akdb/doc/html/
        GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        GH_MAIL: ${{ secrets.YOUR_EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
        EXCLUDED_FILES: "a/ b.md"
